# Auto-generated code, do not edit
set(AB_ENGINE_MAIN
  src/main.cpp
)
set(AB_ENGINE_SOURCES
  src/Rendering/Adapter.cpp
  src/Rendering/Application.cpp
  src/Rendering/BindGroup.cpp
  src/Rendering/BindingLayout.cpp
  src/Rendering/CommandBuffer.cpp
  src/Rendering/Device.cpp
  src/Rendering/Instance.cpp
  src/Rendering/Pipeline.cpp
  src/Rendering/RenderPassCommand.cpp
  src/Rendering/RenderPassEncoder.cpp
  src/Rendering/Shader.cpp
  src/Rendering/VertexBufferLayout.cpp
  src/Rendering/VertexLayout.cpp
  src/asset/assetLoaderFactory.cpp
  src/asset/loadGlb.cpp
  src/demos/loadModel.cpp
  src/math/ceilToBufferOffset.cpp
  src/math/euler.cpp
  src/math/linalg/mat2x2.cpp
  src/math/linalg/mat3x3.cpp
  src/math/linalg/mat4x4.cpp
  src/math/linalg/vec2.cpp
  src/math/linalg/vec3.cpp
  src/math/linalg/vec4.cpp
  src/printStringView.cpp
  src/window/windowFactory.cpp
)
set(AB_ENGINE_SOURCES_NATIVE
  src/asset/NATIVE_assetLoader.cpp
  src/window/NATIVE_glfwWindow.cpp
)
set(AB_ENGINE_SOURCES_WEB
  src/asset/WEB_assetLoader.cpp
  src/window/WEB_canvasWindow.cpp
)
set(AB_ENGINE_TEST_SOURCES
  tests/math/euler.cpp
  tests/math/linalg/mat2x2.cpp
  tests/math/linalg/mat3x3.cpp
  tests/math/linalg/mat4x4.cpp
  tests/math/linalg/vec2.cpp
  tests/math/linalg/vec3.cpp
  tests/math/linalg/vec4.cpp
)
