# Auto-generated code, do not edit
set(PRETOP_ENGINE_MAIN
  src/main.cpp
)
set(PRETOP_ENGINE_SOURCES
  src/Asset/AssetLoaderFactory.cpp
  src/Asset/LoadGlb.cpp
  src/RHI/Adapter.cpp
  src/RHI/Application.cpp
  src/RHI/BindGroup.cpp
  src/RHI/BindingLayout.cpp
  src/RHI/CommandBuffer.cpp
  src/RHI/Device.cpp
  src/RHI/Instance.cpp
  src/RHI/Pipeline.cpp
  src/RHI/RenderPassCommand.cpp
  src/RHI/RenderPassEncoder.cpp
  src/RHI/Shader.cpp
  src/RHI/VertexBufferLayout.cpp
  src/RHI/VertexLayout.cpp
  src/demos/loadModel.cpp
  src/math/ceilToBufferOffset.cpp
  src/math/euler.cpp
  src/math/linalg/mat2x2.cpp
  src/math/linalg/mat3x3.cpp
  src/math/linalg/mat4x4.cpp
  src/math/linalg/vec2.cpp
  src/math/linalg/vec3.cpp
  src/math/linalg/vec4.cpp
  src/printStringView.cpp
  src/window/windowFactory.cpp
)
set(PRETOP_ENGINE_SOURCES_NATIVE
  src/Asset/NATIVE_AssetLoader.cpp
  src/window/NATIVE_glfwWindow.cpp
)
set(PRETOP_ENGINE_SOURCES_WEB
  src/Asset/WEB_AssetLoader.cpp
  src/window/WEB_canvasWindow.cpp
)
set(PRETOP_ENGINE_TEST_SOURCES
  tests/math/euler.cpp
  tests/math/linalg/mat2x2.cpp
  tests/math/linalg/mat3x3.cpp
  tests/math/linalg/mat4x4.cpp
  tests/math/linalg/vec2.cpp
  tests/math/linalg/vec3.cpp
  tests/math/linalg/vec4.cpp
)
