# Auto-generated code, do not edit
set(AB_ENGINE_MAIN
  src/main.cpp
)
set(AB_ENGINE_SOURCES
  src/application/appAdapter.cpp
  src/application/appBindGroup.cpp
  src/application/appBindingLayout.cpp
  src/application/appCommandBuffer.cpp
  src/application/appDevice.cpp
  src/application/appInstance.cpp
  src/application/appPipeline.cpp
  src/application/appRenderPassCommand.cpp
  src/application/appRenderPassEncoder.cpp
  src/application/appShader.cpp
  src/application/appVertexBufferLayout.cpp
  src/application/appVertexLayout.cpp
  src/application/application.cpp
  src/asset/readFileBytes.cpp
  src/math/ceilToBufferOffset.cpp
  src/math/linalg/vec2.cpp
  src/math/linalg/vec3.cpp
  src/printStringView.cpp
  src/window/windowFactory.cpp
)
set(AB_ENGINE_SOURCES_NATIVE
  src/window/NATIVE_glfwWindow.cpp
)
set(AB_ENGINE_SOURCES_WEB
  src/window/WEB_canvasWindow.cpp
)
set(AB_ENGINE_TEST_SOURCES
  tests/math/linalg/vec2.cpp
  tests/math/linalg/vec3.cpp
)
