import os
from pathlib import Path
import platform

PYTHON_LIBRARY_NAME = "pretop"
ENGINE_NAME = "pretop_engine"
NATIVE_TARGET = "pretop_engine"
TEST_TARGET = "pretop_engine_tests"
PYTHON_PACKAGE_TARGET = "pretop_python"

BUILD_DIR = "build"
ENGINE_OUT = f"{BUILD_DIR}/engine"
ENGINE_WEB_OUT = f"{BUILD_DIR}/web-engine"
WEB_SERVER_PORT = 8000

ENGINE_DIR = ".pretop"

ASSET_OUTPUT_DIR = f"{ENGINE_DIR}/assets"
WEB_ASSET_PATH_PREFIX = "assets"

SOURCE_DIR = "source"

GEN_DIR = f"{SOURCE_DIR}/Gen"
GENERATED_CODE_COMMENT = "Generated by Pretop CLI, do not edit"
ASSET_METADATA_DIR = "AssetMetadata"
ASSET_METADATA_OUT = f"{GEN_DIR}/AssetMetadata"
PLATFORM_FILE = f"{SOURCE_DIR}/Core/Platform.hpp"
PLATFORM_INCLUDE_PATH = os.path.relpath(PLATFORM_FILE, start=GEN_DIR)
PLATFORM_INCLUDE = f'#include "{PLATFORM_INCLUDE_PATH}"'
WEB_PLATFORM_DEFINE = f"PRETOP_PLATFORM_WEB"
PRETOP_GEN_NAMESPACE = f"Pretop::Gen"

COMPILER_C = "cl"
COMPILER_CPP = "cl"

if platform.system() == "Linux":
    COMPILER_C = "gcc"
    COMPILER_CPP = "g++"

EXE_SUFFIX = ".exe"
if platform.system() == "Linux":
    EXE_SUFFIX = ""

CMAKE_COMMENT = "#"
CPP_COMMENT = "//"
