# Auto-generated code, do not edit
set(PRETOP_ENGINE_MAIN
  source/main.cpp
)
set(PRETOP_ENGINE_SOURCES
  source/Asset/AssetLoaderFactory.cpp
  source/Asset/AssetManager.cpp
  source/Asset/AssetManagerFactory.cpp
  source/Asset/LoadGlb.cpp
  source/Core/JobSystem.cpp
  source/Demos/LoadModel.cpp
  source/Demos/LoadTexture.cpp
  source/Demos/Texture.cpp
  source/Math/CeilToBufferOffset.cpp
  source/Math/Euler.cpp
  source/Math/Linalg/Mat2x2.cpp
  source/Math/Linalg/Mat3x3.cpp
  source/Math/Linalg/Mat4x4.cpp
  source/Math/Linalg/Vec2.cpp
  source/Math/Linalg/Vec3.cpp
  source/Math/Linalg/Vec4.cpp
  source/PrintStringView.cpp
  source/RHI/Adapter.cpp
  source/RHI/Application.cpp
  source/RHI/BindGroup.cpp
  source/RHI/BindingLayout.cpp
  source/RHI/CommandBuffer.cpp
  source/RHI/Device.cpp
  source/RHI/Instance.cpp
  source/RHI/Pipeline.cpp
  source/RHI/RenderPassCommand.cpp
  source/RHI/RenderPassEncoder.cpp
  source/RHI/Shader.cpp
  source/RHI/VertexBufferLayout.cpp
  source/RHI/VertexLayout.cpp
  source/Utils/NormalizePath.cpp
  source/Window/WindowFactory.cpp
)
set(PRETOP_ENGINE_SOURCES_NATIVE
  source/Asset/NATIVE_AssetLoader.cpp
  source/Window/NATIVE_GlfwWindow.cpp
)
set(PRETOP_ENGINE_SOURCES_PYBIND
  source/PYBIND_Python/Asset.cpp
)
set(PRETOP_ENGINE_SOURCES_WEB
  source/Asset/WEB_AssetLoader.cpp
  source/Window/WEB_CanvasWindow.cpp
)
set(PRETOP_ENGINE_TEST_SOURCES
  tests/Core/JobSystem.cpp
  tests/Core/PagedVector.cpp
  tests/Core/RecordTable.cpp
  tests/Math/Euler.cpp
  tests/Math/Linalg/Mat2x2.cpp
  tests/Math/Linalg/Mat3x3.cpp
  tests/Math/Linalg/Mat4x4.cpp
  tests/Math/Linalg/Vec2.cpp
  tests/Math/Linalg/Vec3.cpp
  tests/Math/Linalg/Vec4.cpp
  tests/Utils/NormalizePath.cpp
)
