# Generated by Pretop CLI, do not edit
set(ASSET_DIR
  .pretop/assets
)
set(VFS_FILES
  models/woolly-mammoth-100k-4096_std.glb
  models/DiffuseTransmissionPlant.glb
  shaders/shader.wgsl
  shaders/textureDemoShader.wgsl
  textures/cobblestoneFloor.png
)
